# config/config.yaml

paths:
  model_dir:   /root/autodl-tmp/runs/models
  results_dir: /root/autodl-tmp/runs/results

data:
  # After the next step, these files will exist:
  train_csv: config/train_split.csv
  val_csv:   config/val_split.csv

  clinical_dir: /root/autodl-tmp/vitiligo/clinical
  wood_dir:     /root/autodl-tmp/vitiligo/wood
  mask_dir:     null
  image_size:   224

model:
  use_cbam: true
  encoder_name: efficientnet-b0
  encoder_weights: imagenet

training:
  batch_size:      16
  num_epochs:      20
  learning_rate:   0.0003   # number (not quoted)
  weight_decay:    0.0001
  seg_loss_weight: 0.0

  scheduler:
    type:     ReduceLROnPlateau
    patience: 3
    factor:   0.5
